### ISSUE TITLE
 DeprecationWarning: numpy boolean subtract

### ISSUE THREAD

**Issue by vinci1it2000** [pandalone/pandalone#10]
Can you fix the warning raised by [this expression](https://github.com/pandalone/pandalone/blob/master/pandalone/xleash/_capture.py#L497). You have to convert the vector to integer otherwise the warning is raised. This is needed for co2mpas [issue](https://github.com/JRCSTU/co2mpas/issues/363).

**Comment by ankostis** [comment]
Cannot convert the vecto to a single integer - maybe you mean the `same_len` in the line immediately below?
@vinci1it2000  can you paste here the warning?

**Comment by vinci1it2000** [comment]
I meant to convert the boolean vector to a an integer vector.

**Comment by ankostis** [comment]
But what is the problem, I still have not understand.
Could it be on the next line, where the index is not an integer?  
Then I should cast only the `same_len`, not the full vector.

Can you paste the warning?

**Comment by ankostis** [comment]
Please paste here the exact numpy-warning.

**Comment by ankostis** [comment]
ping?

**Comment by vinci1it2000** [comment]
The vector that I was mentioning is the `states_vect` that is boolean. `np.diff` is raising the warning.

**Comment by ankostis** [comment]
I'm asking for the numpy-warning to paste it into the commit message.

**Comment by ankostis** [comment]
You see, I cannot get this warning.  
For instance, the following does not raise any warning:

```python
import numpy as np

a=np.array([1,2])
print(np.diff(a>1))
```

**Comment by vinci1it2000** [comment]
Run co2mpas gui and you will see:

     2017-02-25 12:49:35,894:WARNI:py.warnings:/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:1578: 
       DeprecationWarning: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
        return a[slice1]-a[slice2]

**Comment by ankostis** [comment]
fixed in 0.2.3

**Comment by ankostis** [comment]
> Run co2mpas gui and you will see:

By the way, @vinci1it2000 this is not a [MCV example](http://stackoverflow.com/help/mcve) :-)
