### ISSUE TITLE
xlwings brake the installation on Ubuntu.

### ISSUE THREAD

**Issue by vinci1it2000** [pandalone/pandalone#11]
The dependency with xlwings is breaking the installation of pandalone on Ubuntu because xlwings is supported for windows and OSX. Please make it optional.

**Comment by ankostis** [comment]
Making it optional requires also changes in the code for the missing functionality.
Till then, i can use pep508 environment markers.
Besides that would be necessary even If optional.

**Comment by ankostis** [comment]
Now that I checked, I can see that `xlwings` dependency in *pandalone* is ALREADY optional (actually it is an *extra*).
So *xlwings* will be pip-installed only if you app explicitly depends on `pandalone[xlwings]`.

By the way, can write here which *pandalone* version do you have installed?

**Comment by ankostis** [comment]
ping?

**Comment by ankostis** [comment]
@vinci1it2000  I'm waiting your input in #10 to release this one.

**Comment by ankostis** [comment]
Ok, false alarm, problem was actually on *wltp* project(JRCSTU/wltp#3).
