### ISSUE TITLE
xleash lasso mismatch of result rows with excel files having many rows

### ISSUE THREAD

**Issue by ankostis** [pandalone/pandalone#12]
@tansial reported that the result of `datasync.xlsx#:` xref on the following excel file, fails to return the correct array-shape - instead of 268302 rows, 301070 are returned:
[datasync.xlsx](https://github.com/pandalone/pandalone/files/858653/datasync.xlsx)

**Comment by ankostis** [comment]
Code to reproduce it, in a folder containing the excel-file:

```python
import numpy as np
from pandalone import xleash

 np.array(xleash.lasso('datasync.xlsx#:')).shape
(301070, 2)
```

The expected results should be:

```python
(268302, 2)
```

**Comment by ankostis** [comment]
The culprit is [this 16bit linecode](https://github.com/pandalone/pandalone/blob/master/pandalone/xleash/io/backend.py#L302) that identifies the boundaries of the matrix - turning `dtype=int16` --> `int32` works fine.

**Comment by ankostis** [comment]
Fixed in 0.2.4, please @tansial update your *pandalone* and check.

**Comment by ankostis** [comment]
@tansial does it work??

**Comment by tansial** [comment]
Yes, it worked!
